<?php

namespace SergiX44\Gradio\Event;

enum Event: string
{
    case SUBMIT = 'EVENT_SUBMITTED';

    case QUEUE_FULL = 'EVENT_QUEUE_FULL';
    case QUEUE_ESTIMATION = 'EVENT_QUEUE_ESTIMATION';

    case PROCESS_STARTS = 'EVENT_PROCESS_STARTS';
    case PROCESS_COMPLETED = 'EVENT_PROCESS_COMPLETED';

    case PROCESS_SUCCESS = 'EVENT_PROCESS_SUCCESS';
    case PROCESS_FAILED = 'EVENT_PROCESS_FAILED';

}
